# Generated by Django 2.1.7 on 2019-02-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
