# Generated by Django 2.1.7 on 2019-02-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0002_produk_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='deskripsi_produk',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
