# Generated by Django 2.1.7 on 2019-02-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko_online', '0003_produk_deskripsi_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
